<div class="header-block-wrapper clearfix">
	<div class="header-block-inner">
		<a href="conseil.php" class="header-block-5 header-block-style-2 clearfix">
			<i class="fa fa-thumbs-up"></i>
			<h2>Conseil</h2>
		</a>

		<a href="formation.php" class="header-block-5 header-block-style-1 clearfix">
			<i class="fa fa-file-code-o"></i>
			<h2>Formation</h2>
		</a>
		
		<a href="seminaire.php" class="header-block-5 header-block-style-2 clearfix">
			<i class="fa fa-user"></i>
			<h2>Séminaire</h2>
		</a>
	</div>
</div>