<!-- BEGIN .slider -->
	<div class="slider clearfix">
		
		<ul class="slides slide-loader">

			<li style="background:url(assets/images/public/slides/slide_05.jpg) no-repeat bottom center">
				<div class="flex-caption-wrapper">
					<div class="flex-caption">
						<p>Une équipe active et innovante</p>
						
					</div>
				</div>
			</li>
		
			<li style="background:url(assets/images/public/slides/slide_01.jpg) no-repeat bottom center">
				
				<div class="flex-caption-wrapper">
					<div class="flex-caption">
						<p>Un interlocuteur dédié </p>
						
					</div>
				</div>
				
			</li>
			
			<li style="background:url(assets/images/public/slides/slide_02.jpg) no-repeat bottom center">
				
				<div class="flex-caption-wrapper">
					<div class="flex-caption">
						<p>Des tarifs attractifs</p>
						
					</div>
				</div>
				
			</li>
			
			<li style="background:url(assets/images/public/slides/slide_03.jpg) no-repeat bottom center">
				<div class="flex-caption-wrapper">
					<div class="flex-caption">
						<p>Une offre personnalisée selon votre besoin </p>
						
					</div>
				</div>
			</li>

			<li style="background:url(assets/images/public/slides/slide_04.jpg) no-repeat bottom center">
				<div class="flex-caption-wrapper">
					<div class="flex-caption">
						<p>Une qualité de prestation reconnue et appréciée </p>
						
					</div>
				</div>
			</li>

			

		</ul>
		
	<!-- END .slider -->
	</div>